name: Build and Release
on:
  push:
    branches:
      - master

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'zulu'

      - name: Read Version from version.properties
        id: version
        run: echo "::set-output name=version::$(cat version.properties | grep -oP 'version=\K(.*)')"

      - name: Auslesen von CHANGELOG.md
        run: |
          # Verwenden von awk, um den Inhalt von "## AKTUELLE VERSION" bis zur nächsten "##"-Überschrift auszulesen
          awk '/^## ${{ steps.version.outputs.version }}$/,/^##/{if (!/^##$/ && NR>1) {print}}' CHANGELOG.md
        # Die Ausgabe der Auslesung wird als "Ausgabe" des Schritts gespeichert.
        # Sie können die Ausgabe später in anderen Schritten weiterverwenden.
        id: read_changelog_output

      - name: Get Last Commit SHA
        id: commit_sha
        run: echo "::set-output name=commit_sha::$(git rev-parse --short HEAD)"

      - name: Set Gradle Wrapper Permissions
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run build with Gradle Wrapper
        run: ./gradlew clean shadowJar

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            build/libs/PersonalizedFavicon-*.jar
          tag_name: ${{ steps.version.outputs.version }}
          release_name: Release ${{ steps.version.outputs.version }}-${{ steps.commit_sha.outputs.commit_sha }}
          body: ${{ steps.changelog.outputs.changelog }}
