name: release

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java 16 Zulu
        uses: actions/setup-java@v2
        with:
          java-version: "16"
          distribution: "zulu"

      - name: Add Gralew permissions
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew clean shadowJar

      - name: Release
        uses: anton-yurchenko/git-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: build/libs/*.jar